import type { DemoCompany } from "./types";

export const demoCompany: DemoCompany = {
  profile: {
    name: "ABC Manufacturing Pvt. Ltd.",
    industry: "Manufacturing",
    location: "Maharashtra",
    turnover: "₹82 Cr",
    employees: 187,
    fixedAssets: "₹24 Cr",
    inventory: "₹9.4 Cr",
    yearsOperating: 12,
    facts: [
      { label: "Annual turnover", value: "₹82 Cr", source: "Audited financials FY24" },
      { label: "Employees", value: "187", source: "Employee register" },
      { label: "Fixed assets", value: "₹24 Cr", source: "Balance sheet" },
      { label: "Inventory", value: "₹9.4 Cr", source: "Balance sheet" },
      { label: "Years in business", value: "12", source: "Incorporation records" },
    ],
    findings: [
      "Physical manufacturing operations",
      "Significant fixed asset base",
      "Material inventory exposure",
      "187 employees",
      "Existing property/fire insurance",
      "Employee personal accident coverage",
      "No business interruption cover identified",
      "No cyber cover identified",
    ],
  },
  coverage: [
    { key: "property", label: "Property", status: "covered", coverIdentified: "₹20 Cr" },
    { key: "fire", label: "Fire", status: "covered", coverIdentified: "₹20 Cr" },
    { key: "pa", label: "Employee PA", status: "covered", coverIdentified: "₹2L / employee" },
    { key: "liability", label: "Liability", status: "review", coverIdentified: "₹1 Cr" },
    { key: "bi", label: "Business Interruption", status: "not-identified", coverIdentified: "—" },
    { key: "cyber", label: "Cyber", status: "not-identified", coverIdentified: "—" },
  ],
  scores: {
    overall: 64,
    whyBullets: [
      "Strong property protection identified",
      "Employee PA already in place",
      "No business interruption protection identified",
      "Cyber protection not identified",
      "Liability coverage may warrant review",
    ],
    categories: [
      { key: "property", label: "Property", score: 82, determination: {
        facts: ["Manufacturing site with significant fixed assets (₹24 Cr)"],
        evidence: ["Property cover ₹20 Cr identified", "Fire cover ₹20 Cr identified"],
        assessment: "Property and fire protection appear well established." } },
      { key: "business-continuity", label: "Business Continuity", score: 38, determination: {
        facts: ["Operations depend on physical assets and inventory (₹9.4 Cr)"],
        evidence: ["No business interruption cover identified in documents reviewed"],
        assessment: "A disruption could affect revenue and fixed expenses; business interruption protection may warrant review.",
        recommendationRef: "reco-business-continuity" } },
      { key: "liability", label: "Liability", score: 56, determination: {
        facts: ["₹82 Cr turnover; manufacturing operations"],
        evidence: ["Liability cover ₹1 Cr identified"],
        assessment: "Current liability protection may warrant review relative to business scale." } },
      { key: "cyber", label: "Cyber", score: 25, determination: {
        facts: ["187 employees", "Manufacturing business", "Customer and vendor data handled"],
        evidence: ["No cyber policy identified in uploaded documents"],
        assessment: "Cyber exposure may warrant review.",
        recommendationRef: "reco-cyber" } },
      { key: "people", label: "People", score: 67, determination: {
        facts: ["187 employees", "Employee PA ₹2L per employee in place"],
        evidence: ["No group health identified"],
        assessment: "Employee protection is present with opportunities to broaden health benefits.",
        recommendationRef: "reco-employee" } },
      { key: "other", label: "Other", score: 72, determination: {
        facts: ["Established 12-year operating history"],
        evidence: ["Core asset protections identified"],
        assessment: "Remaining areas appear reasonably addressed based on information provided." } },
    ],
  },
  risks: [
    { key: "business-continuity", title: "Business continuity", severity: "high",
      why: "Your operations depend significantly on physical assets, but business interruption protection was not identified.",
      evidence: ["Manufacturing operation", "Fixed assets ₹24 Cr", "Inventory ₹9.4 Cr", "No BI cover in documents reviewed"],
      whatYouCanDo: "Review suitable business interruption options with CoverSure.",
      determination: { facts: ["Physical-asset-dependent operations","Inventory ₹9.4 Cr"], evidence: ["No BI cover identified"], assessment: "Business interruption protection may warrant review.", recommendationRef: "reco-business-continuity" } },
    { key: "employee", title: "Employee protection", severity: "attention",
      why: "Employee PA is present, but broader employee protection opportunities may exist.",
      evidence: ["Employee PA ₹2L per employee identified", "No group health identified"],
      whatYouCanDo: "Explore enhanced employee protection and health benefits.",
      determination: { facts: ["187 employees","PA in place"], evidence: ["No group health identified"], assessment: "Broader employee protection may warrant review.", recommendationRef: "reco-employee" } },
    { key: "liability", title: "Liability", severity: "review",
      why: "Current liability protection may warrant review based on your business scale and operations.",
      evidence: ["Liability cover ₹1 Cr identified", "₹82 Cr turnover"],
      whatYouCanDo: "Review liability limits with CoverSure.",
      determination: { facts: ["₹82 Cr turnover"], evidence: ["Liability cover ₹1 Cr"], assessment: "Liability limits may warrant review." } },
    { key: "cyber", title: "Cyber", severity: "high",
      why: "No cyber protection was identified in the documents reviewed.",
      evidence: ["Customer/vendor data handled", "No cyber policy identified"],
      whatYouCanDo: "Explore cyber protection options.",
      determination: { facts: ["Data handled","187 employees"], evidence: ["No cyber policy identified"], assessment: "Cyber exposure may warrant review.", recommendationRef: "reco-cyber" } },
    { key: "property", title: "Property", severity: "good",
      why: "Property and fire protection were identified.",
      evidence: ["Property ₹20 Cr", "Fire ₹20 Cr"],
      whatYouCanDo: "Maintain current cover; review periodically.",
      determination: { facts: ["Fixed assets ₹24 Cr"], evidence: ["Property & fire ₹20 Cr each"], assessment: "Property protection appears well established." } },
  ],
  benefits: {
    peopleScore: 67, benefitsScore: 43, employees: 187,
    items: [
      { label: "Personal Accident", provided: true, category: "Protection" },
      { label: "Group Health", provided: false, category: "Protection" },
      { label: "Doctor consultations", provided: false, category: "Health" },
      { label: "Specialist consultations", provided: false, category: "Health" },
      { label: "Diagnostics", provided: false, category: "Health" },
      { label: "Medicines", provided: false, category: "Health" },
      { label: "Nutrition", provided: false, category: "Wellbeing" },
      { label: "Preventive health", provided: false, category: "Wellbeing" },
      { label: "Wellness support", provided: false, category: "Wellbeing" },
      { label: "Family health support", provided: false, category: "Family" },
      { label: "Family benefits", provided: false, category: "Family" },
    ],
  },
  recommendations: [
    { id: "reco-business-continuity", index: "01", title: "Protect business continuity", priority: "high",
      why: "Your business has significant operational assets and inventory, but we could not identify business interruption protection.",
      recommended: "Business Interruption Protection",
      found: [
        { label: "Manufacturing operation", present: true },
        { label: "₹82 Cr annual turnover", present: true },
        { label: "Significant fixed assets", present: true },
        { label: "Material inventory", present: true },
        { label: "Business interruption protection", present: false },
      ],
      couldBeConsidered: "Business Interruption cover can potentially help protect against financial losses following an insured interruption, subject to policy terms and underwriting.",
      coversureCanHelp: "We can help you review suitable options and obtain quotes.",
      determination: { facts: ["Manufacturing operation","₹82 Cr turnover","Significant fixed assets","Material inventory"], evidence: ["Business interruption protection not identified"], assessment: "Business interruption protection may warrant review." } },
    { id: "reco-employee", index: "02", title: "Strengthen employee protection", priority: "high",
      why: "Your 187 employees have personal accident protection, but there may be an opportunity to provide broader protection and health benefits.",
      recommended: "Enhanced Employee Protection + Health",
      found: [
        { label: "187 employees", present: true },
        { label: "Personal accident protection", present: true },
        { label: "Group health", present: false },
      ],
      couldBeConsidered: "Broader employee protection and group health benefits can potentially improve wellbeing and retention, subject to policy terms and underwriting.",
      coversureCanHelp: "We can help you review suitable options and obtain quotes.",
      determination: { facts: ["187 employees","PA in place"], evidence: ["No group health identified"], assessment: "Broader employee protection may warrant review." } },
    { id: "reco-cyber", index: "03", title: "Review cyber exposure", priority: "medium",
      why: "Your business handles operational and business data, but cyber protection was not identified in the documents reviewed.",
      recommended: "Cyber Protection",
      found: [
        { label: "Operational & business data handled", present: true },
        { label: "Cyber protection", present: false },
      ],
      couldBeConsidered: "Cyber cover can potentially help respond to data and systems incidents, subject to policy terms and underwriting.",
      coversureCanHelp: "We can help you review suitable options and obtain quotes.",
      determination: { facts: ["Data handled","187 employees"], evidence: ["No cyber policy identified"], assessment: "Cyber exposure may warrant review." } },
  ],
  seededRequests: [],
};
